config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#root'
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save!
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Controller responsible for handling the welcome page
class WelcomeController < ApplicationController
  def root
    render 'root'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">RailsTaskManager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'New Task', tasks_new_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @task do |f| %>
        <h2 class="text-center mb-4">Edit Task</h2>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :details %>
          <%= f.text_area :details, class: "form-control" %>
        </div>

        <div class="form-group form-check">
          <%= f.label :completed, class: "form-check-label" do %>
            <%= f.check_box :completed, class: "form-check-input" %>
            Completed
          <% end %>
        </div>

        <%= f.submit "Update Task", class: "btn btn-primary btn-block mt-4" %>
      <% end %>

      <%= link_to "Go back", tasks_path, class: "btn btn-secondary btn-block mt-2" %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">All tasks</h1>

  <ul class="list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span class="task-status <%= task.completed ? 'completed' : 'not-completed' %>">
          <i class="fas <%= task.completed ? 'fa-check'.html_safe : 'fa-times'.html_safe %>"></i>
        </span>
        <%= link_to task.title, task_path(task), class: 'task-link' %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Add a new task', tasks_new_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <%= form_with model: @task, class: 'task-form' do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :details %>
              <%= f.text_field :details, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :completed %>
              <%= f.check_box :completed, class: 'form-check-input' %>
            </div>
            <%= f.submit 'Save', class: 'btn btn-primary' %>
          <% end %>
        </div>
        <div class="card-footer">
          <button type="button" class="btn btn-secondary"><%= link_to 'Go back', tasks_path %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Task: <%= @task.title %></h2>
          <p class="card-text"><%= @task.details %></p>
          <p class="card-text">
            <span id="status-icon" class="<%= @task.completed ? 'completed' : 'not-completed' %>">
              <i id="status-toggle" class="fas <%= @task.completed ? 'fa-check'.html_safe : 'fa-times'.html_safe %>"></i>
            </span>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to "Delete", task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" }, class: 'btn btn-danger' %>
          <%= link_to 'Go back', tasks_path, class: 'btn btn-secondary' %>
          <%= link_to 'Edit Task', tasks_edit_path(@task), class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const statusToggle = document.getElementById("status-toggle");
    const statusIcon = document.getElementById("status-icon");

    statusToggle.addEventListener("click", function() {
      if (statusIcon.classList.contains("completed")) {
        statusIcon.classList.remove("completed");
        statusIcon.classList.add("not-completed");
        statusToggle.classList.remove("fa-check");
        statusToggle.classList.add("fa-times");
      } else {
        statusIcon.classList.remove("not-completed");
        statusIcon.classList.add("completed");
        statusToggle.classList.remove("fa-times");
        statusToggle.classList.add("fa-check");
      }
    });
  });
</script>

app/views/welcome/root.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <!-- Your welcome card content here -->
    <div class="card mx-auto mt-5" style="width: 400px;">
      <div class="card-body">
        <h1 class="card-title">Welcome to RailsTaskManager!</h1>
        <p class="card-text">This is the landing page for your application.</p>
        <p class="card-text">Customize it as per your requirements.</p>
        <a href="/tasks" class="btn btn-primary">Get Started</a>
      </div>
    </div>
  </body>
</html>